### PR TITLE
Adds counter and removes extra variable

### PR DESCRIPTION
**Pull request by bark4mark**

### CODE REVIEW

**Review by icemanparachute — COMMENTED** [review]
if we switch to using counters, we have to increment before we do any other state changing events to remove any possibilities of reentrancy. So we should set the counter to a variable first, then increment and then do all of the additional functions after.

**Comment by icemanparachute** [comment]
I'm also still thinking through the version of this contract vs the one in the examples branch where the mapping isn't stored in the struct - still a wip i think

**Comment by bark4mark** [comment]
Cool, I just wanted to get your opinion on this. Would the ReentrancyGuard not stop any reentrancy attacks?

**Comment by bark4mark** [comment]
Also do you know if there is any benefit to using the counter? I was just looking at some examples and it was in use, when I look at the code it is just an integer variable.

**Pull request closed without merging**
